#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Get the hostname
hostname=$(hostname)

# Configure Nginx with custom header
echo "add_header X-Served-By $hostname;" | sudo tee -a /etc/nginx/nginx.conf

# Restart Nginx to apply changes
sudo systemctl restart nginx
